// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sofia.Data.Contexts;

namespace Sofia.Data.Migrations
{
    [DbContext(typeof(SofiaDbContext))]
    [Migration("20190505014542_contributions")]
    partial class contributions
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sofia.Data.Models.Contribution", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActivityId");

                    b.Property<int>("ContributionType");

                    b.Property<string>("ContributorEmail");

                    b.Property<string>("ContributorGithubId");

                    b.Property<long>("ContributorId");

                    b.Property<string>("ContributorName");

                    b.Property<long>("FileId");

                    b.HasKey("Id");

                    b.HasIndex("ContributorId");

                    b.HasIndex("FileId");

                    b.ToTable("Contributions");
                });

            modelBuilder.Entity("Sofia.Data.Models.Contributor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CanonicalName");

                    b.Property<string>("GitHubLogin");

                    b.Property<long>("SubscriptionId");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("Contributors");
                });

            modelBuilder.Entity("Sofia.Data.Models.File", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CanonicalName");

                    b.Property<long>("SubscriptionId");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("Sofia.Data.Models.FileHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommitSha");

                    b.Property<long>("ContributionId");

                    b.Property<int>("FileHistoryType");

                    b.Property<long>("FileId");

                    b.HasKey("Id");

                    b.HasIndex("ContributionId");

                    b.HasIndex("FileId");

                    b.ToTable("FileHistories");
                });

            modelBuilder.Entity("Sofia.Data.Models.Subscription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Branch");

                    b.Property<string>("GitHubRepositoryUrl");

                    b.Property<string>("LocalRepositoryPath");

                    b.Property<string>("OauthToken");

                    b.Property<string>("Owner");

                    b.Property<string>("Repo");

                    b.Property<DateTime>("SubscriptionDateTime");

                    b.HasKey("Id");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Sofia.Data.Models.SubscriptionEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("EndDateTime");

                    b.Property<DateTime>("StartDateTime");

                    b.Property<int>("SubscriptionEventType");

                    b.Property<long>("SubscriptionId");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("SubscriptionEvent");
                });

            modelBuilder.Entity("Sofia.Data.Models.Contribution", b =>
                {
                    b.HasOne("Sofia.Data.Models.Contributor", "Contributor")
                        .WithMany("Contributions")
                        .HasForeignKey("ContributorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Sofia.Data.Models.File", "File")
                        .WithMany("Contributions")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Sofia.Data.Models.Contributor", b =>
                {
                    b.HasOne("Sofia.Data.Models.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Sofia.Data.Models.File", b =>
                {
                    b.HasOne("Sofia.Data.Models.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Sofia.Data.Models.FileHistory", b =>
                {
                    b.HasOne("Sofia.Data.Models.Contribution", "Contribution")
                        .WithMany()
                        .HasForeignKey("ContributionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Sofia.Data.Models.File", "File")
                        .WithMany("FileHistories")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Sofia.Data.Models.SubscriptionEvent", b =>
                {
                    b.HasOne("Sofia.Data.Models.Subscription", "Subscription")
                        .WithMany("SubscriptionEvents")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
